language: objective-c
env:
  global:
  - APP_NAME="SwiftOverlays"czx
before_script:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script:
  - xctool -project Example/Example.xcodeproj -scheme SwiftOverlays-example-debug -sdk iphonesimulator8.1 test