language: objective-c
osx_image: beta-xcode6.3
env:
  global:
  - APP_NAME="SwiftOverlays"
before_script:
  - brew update
  - brew outdated xctool || brew upgrade xctool
script:
  - xctool -project Example/Example.xcodeproj -scheme SwiftOverlays-example-debug -sdk iphonesimulator8.3 test